server:
  port: ${PORT:8080}
  
zuul:
  ignoredServices: '*'
  routes:
    order:
      path: /order/**
      url: http://localhost:8090
    businness:
      path: /businness/**
      url: http://localhost:8091
    product:
      path: /product/**
      url: http://localhost:8092